server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /media

spring:
  profiles:
    default: local

  jpa:
    open-in-view: true

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
