spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://15.165.148.96:3306/sohot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sohot
    password: 1howtobiz
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create #추후에 validate
    properties:
      hibernate:
        #          show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
log:
  config:
    path: ./logs
    filename: app-dev
    maxHistory: 10
    totalSizeCap: 30MB
  level:
    org.hibernate.type: trace
    com.zaxxer.hikari.HikariConfig: trace
    com.zaxxer.hikari: trace


cloud:
  aws:
    credentials:
      instance-profile: false
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false

aws:
  s3:
    bucket: ${BUCKET}

file:
  path: /home/jms
  videoModel: exec.py
  audioModel: exec.py