spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
log:
  config:
    path: ./logs
    filename: app-local
    maxHistory: 10
    totalSizeCap: 30MB